### ISSUE TITLE
Error during revocation

### ISSUE THREAD

**Issue by mastavralis** [ukrbublik/openssl_x509_gencrl#2]
Hello, in genral the library works very good, well done.
However, sometimes I have an issue while I am trying to make a revoke. The error I get is the following: Please note, that it doesn't happen every time I am revoking a certificate.

Exception

Can't parse time from string '170504141126Z'! Parse errors: A two digit second could not be found; Data missing

Can you please guide about the error and how to solve it? 

Thank you.

**Comment by ukrbublik** [comment]
Hi.
Check latest commit, should fix this issue:
https://github.com/ukrbublik/openssl_x509_gencrl/commit/8d6c8c8ff93a62bf75f5445048cb0e4ef663c83c

Thanks for interest in this lib. I'm glad if you find it useful for your projects. PS. You can add star :)

**Comment by mastavralis** [comment]
It work fine now, thank you :)
